import { chromium } from "playwright-core";
const S = process.argv[2] || "./shots";
import { mkdirSync } from "node:fs";
mkdirSync(S, { recursive: true });
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH, args: ["--no-sandbox"] });
const page = await b.newPage({ viewport: { width: 1360, height: 1000 } });
const errors = []; page.on("pageerror", (e) => errors.push(e.message));
const base = process.env.BASE || "http://localhost:3100";
await page.goto(base + "/login"); await page.fill("input[name=password]", "pw123");
await Promise.all([page.waitForURL(base + "/"), page.click("button")]);
await page.goto(base + "/studio/chat");
await page.fill("textarea >> nth=0", "We cut reporting time by 60%.");
await page.fill("textarea[placeholder^='Ask a question']", "Give me a sharper opening");
await page.keyboard.press("Enter");
await page.waitForSelector(".chatmsg.assistant:not(.hint)", { timeout: 20000 });
await page.fill("textarea[placeholder^='Ask a question']", "Shorter please");
await page.click("button:has-text('Ask')");
await page.waitForFunction(() => document.querySelectorAll(".chatmsg.assistant").length >= 2, null, { timeout: 20000 });
console.log("messages:", await page.locator(".chatmsg").count());
await page.screenshot({ path: `${S}/n-chat.png`, fullPage: true });
await page.click("button:has-text('Use as the draft') >> nth=0"); await page.waitForURL(/\/studio\/[a-z0-9]+$/);
await page.waitForSelector("text=Ask the writing assistant");
await page.fill("textarea[placeholder^='Ask a question']", "What is weak about this?");
await page.click("button:has-text('Ask')"); await page.waitForSelector(".chatmsg.assistant:not(.hint)", { timeout: 20000 });
await page.screenshot({ path: `${S}/n-chat-editor.png`, fullPage: false });
console.log("ERRORS", JSON.stringify(errors));
await b.close();
